test open

diff --git a/.github/workflows/deploy.yaml b/.github/workflows/deploy.yaml
--- a/.github/workflows/deploy.yaml
+++ b/.github/workflows/deploy.yaml
@@ -17,8 +17,8 @@ jobs:
         run: npm install
       - name : Run Tests
         run: ./node_modules/.bin/nyc --reporter=html ./node_modules/.bin/mocha --reporter mochawesome
-      - name : exit with error if tests fail
-        run: exit 1
+    #   - name : exit with error if tests fail
+    #     run: exit 1
           
 
   if_merged:
